AllCops:
  Exclude:
    - 'old/**/*'

Layout/CaseIndentation:
  Enabled: false
Layout/ElseAlignment:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Layout/LeadingCommentSpace:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false
Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Style/MixinUsage:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/RedundantBegin:
  Enabled: false
Style/WhileUntilModifier:
  Enabled: false
